sudo rm /usr/local/share/licenses/cv2/opencl-headers-LICENSE.txt
sudo rm /usr/local/include/cv2/opencv2/cvconfig.h
sudo rm /usr/local/include/cv2/opencv2/opencv_modules.hpp
sudo rm /usr/local/lib/cmake/cv2/OpenCVModules.cmake
sudo rm /usr/local/lib/cmake/cv2/OpenCVModules-release.cmake
sudo rm /usr/local/lib/cmake/cv2/OpenCVConfig-version.cmake
sudo rm /usr/local/lib/cmake/cv2/OpenCVConfig.cmake
sudo rm /usr/local/bin/setup_vars_cv2.sh
sudo rm /usr/local/share/cv2/valgrind.supp
sudo rm /usr/local/share/cv2/valgrind_3rdparty.supp
sudo rm /usr/local/share/licenses/cv2/libjpeg-turbo-README.md
sudo rm /usr/local/share/licenses/cv2/libjpeg-turbo-LICENSE.md
sudo rm /usr/local/share/licenses/cv2/libjpeg-turbo-README.ijg
sudo rm /usr/local/share/licenses/cv2/libtiff-COPYRIGHT
sudo rm /usr/local/share/licenses/cv2/jasper-LICENSE
sudo rm /usr/local/share/licenses/cv2/jasper-README
sudo rm /usr/local/share/licenses/cv2/jasper-copyright
sudo rm /usr/local/share/licenses/cv2/openexr-LICENSE
sudo rm /usr/local/share/licenses/cv2/openexr-AUTHORS.ilmbase
sudo rm /usr/local/share/licenses/cv2/openexr-AUTHORS.openexr
sudo rm /usr/local/share/licenses/cv2/openexr-fix_msvc2013_errors.patch
sudo rm /usr/local/share/licenses/cv2/protobuf-LICENSE
sudo rm /usr/local/share/licenses/cv2/protobuf-README.md
sudo rm /usr/local/share/licenses/cv2/quirc-LICENSE
sudo rm /usr/local/include/cv2/opencv2/opencv.hpp
sudo rm /usr/local/share/licenses/cv2/ade-LICENSE
sudo rm /usr/local/python/setup.py
sudo rm /usr/local/python/cv2/__init__.py
sudo rm /usr/local/python/cv2/load_config_py2.py
sudo rm /usr/local/python/cv2/load_config_py3.py
sudo rm /usr/local/python/cv2/config.py
sudo rm /usr/local/lib/libopencv_cudev.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudev.so.4.0
sudo rm /usr/local/lib/libopencv_cudev.so
sudo rm /usr/local/include/cv2/opencv2/cudev/block/block.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/detail/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/detail/reduce_key_val.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/dynamic_smem.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/scan.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/block/vec_distance.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/common.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/binary_func.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/binary_op.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/color.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/deriv.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/expr.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/per_element_func.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/reduction.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/unary_func.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/unary_op.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/expr/warping.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/functional/color_cvt.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/functional/detail/color_cvt.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/functional/functional.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/functional/tuple_adapter.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/copy.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/copy.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/histogram.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/integral.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/minmaxloc.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/pyr_down.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/pyr_up.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/reduce_to_column.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/reduce_to_row.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/split_merge.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/transform.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/detail/transpose.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/histogram.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/integral.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/pyramids.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/reduce_to_vec.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/split_merge.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/transform.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/grid/transpose.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/constant.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/deriv.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/detail/gpumat.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/extrapolation.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/glob.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/gpumat.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/interpolation.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/lut.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/mask.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/remap.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/resize.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/texture.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/traits.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/transform.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/warping.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/ptr2d/zip.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/atomic.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/detail/tuple.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/detail/type_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/limits.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/saturate_cast.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/simd_functions.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/tuple.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/type_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/vec_math.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/util/vec_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/detail/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/detail/reduce_key_val.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/scan.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/shuffle.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/warp/warp.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev.hpp
sudo rm /usr/local/include/cv2/opencv2/cudev/common.hpp
sudo rm /usr/local/lib/libopencv_core.so.4.0.0
sudo rm /usr/local/lib/libopencv_core.so.4.0
sudo rm /usr/local/lib/libopencv_core.so
sudo rm /usr/local/include/cv2/opencv2/core/opencl/ocl_defs.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/opencl_info.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/opencl_svm.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_clamdblas.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_clamdfft.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_core.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_gl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_svm_20.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/block.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/border_interpolate.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/color.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/common.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/datamov_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/dynamic_smem.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/emulation.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/filters.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/funcattrib.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/functional.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/limits.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/saturate_cast.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/scan.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/simd_functions.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/transform.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/type_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/utility.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/vec_distance.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/vec_math.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/vec_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/warp.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/warp_reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/warp_shuffle.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/color_detail.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/reduce.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/reduce_key_val.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/transform_detail.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/type_traits_detail.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda/detail/vec_distance_detail.hpp
sudo rm /usr/local/include/cv2/opencv2/core.hpp
sudo rm /usr/local/include/cv2/opencv2/core/affine.hpp
sudo rm /usr/local/include/cv2/opencv2/core/base.hpp
sudo rm /usr/local/include/cv2/opencv2/core/bindings_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/core/bufferpool.hpp
sudo rm /usr/local/include/cv2/opencv2/core/check.hpp
sudo rm /usr/local/include/cv2/opencv2/core/core.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda.inl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda_stream_accessor.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cuda_types.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cvstd.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cvstd.inl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/cvstd_wrapper.hpp
sudo rm /usr/local/include/cv2/opencv2/core/directx.hpp
sudo rm /usr/local/include/cv2/opencv2/core/eigen.hpp
sudo rm /usr/local/include/cv2/opencv2/core/fast_math.hpp
sudo rm /usr/local/include/cv2/opencv2/core/mat.hpp
sudo rm /usr/local/include/cv2/opencv2/core/mat.inl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/matx.hpp
sudo rm /usr/local/include/cv2/opencv2/core/neon_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/core/ocl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/ocl_genbase.hpp
sudo rm /usr/local/include/cv2/opencv2/core/opengl.hpp
sudo rm /usr/local/include/cv2/opencv2/core/operations.hpp
sudo rm /usr/local/include/cv2/opencv2/core/optim.hpp
sudo rm /usr/local/include/cv2/opencv2/core/ovx.hpp
sudo rm /usr/local/include/cv2/opencv2/core/persistence.hpp
sudo rm /usr/local/include/cv2/opencv2/core/saturate.hpp
sudo rm /usr/local/include/cv2/opencv2/core/softfloat.hpp
sudo rm /usr/local/include/cv2/opencv2/core/sse_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/core/traits.hpp
sudo rm /usr/local/include/cv2/opencv2/core/types.hpp
sudo rm /usr/local/include/cv2/opencv2/core/utility.hpp
sudo rm /usr/local/include/cv2/opencv2/core/va_intel.hpp
sudo rm /usr/local/include/cv2/opencv2/core/version.hpp
sudo rm /usr/local/include/cv2/opencv2/core/vsx_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/core/core_c.h
sudo rm /usr/local/include/cv2/opencv2/core/cv_cpu_dispatch.h
sudo rm /usr/local/include/cv2/opencv2/core/cv_cpu_helper.h
sudo rm /usr/local/include/cv2/opencv2/core/cvdef.h
sudo rm /usr/local/include/cv2/opencv2/core/types_c.h
sudo rm /usr/local/include/cv2/opencv2/core/hal/hal.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_avx.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_cpp.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_forward.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_neon.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_sse.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_sse_em.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/intrin_vsx.hpp
sudo rm /usr/local/include/cv2/opencv2/core/hal/interface.h
sudo rm /usr/local/include/cv2/opencv2/core/utils/filesystem.hpp
sudo rm /usr/local/include/cv2/opencv2/core/utils/logger.defines.hpp
sudo rm /usr/local/include/cv2/opencv2/core/utils/logger.hpp
sudo rm /usr/local/include/cv2/opencv2/core/utils/trace.hpp
sudo rm /usr/local/share/licenses/cv2/SoftFloat-COPYING.txt
sudo rm /usr/local/lib/libopencv_cudaarithm.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudaarithm.so.4.0
sudo rm /usr/local/lib/libopencv_cudaarithm.so
sudo rm /usr/local/include/cv2/opencv2/cudaarithm.hpp
sudo rm /usr/local/lib/libopencv_flann.so.4.0.0
sudo rm /usr/local/lib/libopencv_flann.so.4.0
sudo rm /usr/local/lib/libopencv_flann.so
sudo rm /usr/local/include/cv2/opencv2/flann.hpp
sudo rm /usr/local/include/cv2/opencv2/flann/flann.hpp
sudo rm /usr/local/include/cv2/opencv2/flann/flann_base.hpp
sudo rm /usr/local/include/cv2/opencv2/flann/miniflann.hpp
sudo rm /usr/local/include/cv2/opencv2/flann/all_indices.h
sudo rm /usr/local/include/cv2/opencv2/flann/allocator.h
sudo rm /usr/local/include/cv2/opencv2/flann/any.h
sudo rm /usr/local/include/cv2/opencv2/flann/autotuned_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/composite_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/config.h
sudo rm /usr/local/include/cv2/opencv2/flann/defines.h
sudo rm /usr/local/include/cv2/opencv2/flann/dist.h
sudo rm /usr/local/include/cv2/opencv2/flann/dummy.h
sudo rm /usr/local/include/cv2/opencv2/flann/dynamic_bitset.h
sudo rm /usr/local/include/cv2/opencv2/flann/general.h
sudo rm /usr/local/include/cv2/opencv2/flann/ground_truth.h
sudo rm /usr/local/include/cv2/opencv2/flann/heap.h
sudo rm /usr/local/include/cv2/opencv2/flann/hierarchical_clustering_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/index_testing.h
sudo rm /usr/local/include/cv2/opencv2/flann/kdtree_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/kdtree_single_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/kmeans_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/linear_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/logger.h
sudo rm /usr/local/include/cv2/opencv2/flann/lsh_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/lsh_table.h
sudo rm /usr/local/include/cv2/opencv2/flann/matrix.h
sudo rm /usr/local/include/cv2/opencv2/flann/nn_index.h
sudo rm /usr/local/include/cv2/opencv2/flann/object_factory.h
sudo rm /usr/local/include/cv2/opencv2/flann/params.h
sudo rm /usr/local/include/cv2/opencv2/flann/random.h
sudo rm /usr/local/include/cv2/opencv2/flann/result_set.h
sudo rm /usr/local/include/cv2/opencv2/flann/sampling.h
sudo rm /usr/local/include/cv2/opencv2/flann/saving.h
sudo rm /usr/local/include/cv2/opencv2/flann/simplex_downhill.h
sudo rm /usr/local/include/cv2/opencv2/flann/timer.h
sudo rm /usr/local/lib/libopencv_imgproc.so.4.0.0
sudo rm /usr/local/lib/libopencv_imgproc.so.4.0
sudo rm /usr/local/lib/libopencv_imgproc.so
sudo rm /usr/local/include/cv2/opencv2/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/imgproc/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/imgproc/imgproc_c.h
sudo rm /usr/local/include/cv2/opencv2/imgproc/types_c.h
sudo rm /usr/local/include/cv2/opencv2/imgproc/hal/hal.hpp
sudo rm /usr/local/include/cv2/opencv2/imgproc/hal/interface.h
sudo rm /usr/local/include/cv2/opencv2/imgproc/detail/gcgraph.hpp
sudo rm /usr/local/lib/libopencv_ml.so.4.0.0
sudo rm /usr/local/lib/libopencv_ml.so.4.0
sudo rm /usr/local/lib/libopencv_ml.so
sudo rm /usr/local/include/cv2/opencv2/ml.hpp
sudo rm /usr/local/include/cv2/opencv2/ml/ml.hpp
sudo rm /usr/local/include/cv2/opencv2/ml/ml.inl.hpp
sudo rm /usr/local/lib/libopencv_phase_unwrapping.so.4.0.0
sudo rm /usr/local/lib/libopencv_phase_unwrapping.so.4.0
sudo rm /usr/local/lib/libopencv_phase_unwrapping.so
sudo rm /usr/local/include/cv2/opencv2/phase_unwrapping.hpp
sudo rm /usr/local/include/cv2/opencv2/phase_unwrapping/histogramphaseunwrapping.hpp
sudo rm /usr/local/include/cv2/opencv2/phase_unwrapping/phase_unwrapping.hpp
sudo rm /usr/local/lib/libopencv_plot.so.4.0.0
sudo rm /usr/local/lib/libopencv_plot.so.4.0
sudo rm /usr/local/lib/libopencv_plot.so
sudo rm /usr/local/include/cv2/opencv2/plot.hpp
sudo rm /usr/local/lib/libopencv_reg.so.4.0.0
sudo rm /usr/local/lib/libopencv_reg.so.4.0
sudo rm /usr/local/lib/libopencv_reg.so
sudo rm /usr/local/include/cv2/opencv2/reg/map.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mapaffine.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mapper.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mappergradaffine.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mappergradeuclid.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mappergradproj.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mappergradshift.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mappergradsimilar.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mapperpyramid.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mapprojec.hpp
sudo rm /usr/local/include/cv2/opencv2/reg/mapshift.hpp
sudo rm /usr/local/lib/libopencv_surface_matching.so.4.0.0
sudo rm /usr/local/lib/libopencv_surface_matching.so.4.0
sudo rm /usr/local/lib/libopencv_surface_matching.so
sudo rm /usr/local/include/cv2/opencv2/surface_matching.hpp
sudo rm /usr/local/include/cv2/opencv2/surface_matching/icp.hpp
sudo rm /usr/local/include/cv2/opencv2/surface_matching/pose_3d.hpp
sudo rm /usr/local/include/cv2/opencv2/surface_matching/ppf_helpers.hpp
sudo rm /usr/local/include/cv2/opencv2/surface_matching/ppf_match_3d.hpp
sudo rm /usr/local/include/cv2/opencv2/surface_matching/t_hash_int.hpp
sudo rm /usr/local/lib/libopencv_xphoto.so.4.0.0
sudo rm /usr/local/lib/libopencv_xphoto.so.4.0
sudo rm /usr/local/lib/libopencv_xphoto.so
sudo rm /usr/local/include/cv2/opencv2/xphoto.hpp
sudo rm /usr/local/include/cv2/opencv2/xphoto/bm3d_image_denoising.hpp
sudo rm /usr/local/include/cv2/opencv2/xphoto/dct_image_denoising.hpp
sudo rm /usr/local/include/cv2/opencv2/xphoto/inpainting.hpp
sudo rm /usr/local/include/cv2/opencv2/xphoto/oilpainting.hpp
sudo rm /usr/local/include/cv2/opencv2/xphoto/white_balance.hpp
sudo rm /usr/local/lib/libopencv_cudafilters.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudafilters.so.4.0
sudo rm /usr/local/lib/libopencv_cudafilters.so
sudo rm /usr/local/include/cv2/opencv2/cudafilters.hpp
sudo rm /usr/local/lib/libopencv_cudaimgproc.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudaimgproc.so.4.0
sudo rm /usr/local/lib/libopencv_cudaimgproc.so
sudo rm /usr/local/include/cv2/opencv2/cudaimgproc.hpp
sudo rm /usr/local/lib/libopencv_cudawarping.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudawarping.so.4.0
sudo rm /usr/local/lib/libopencv_cudawarping.so
sudo rm /usr/local/include/cv2/opencv2/cudawarping.hpp
sudo rm /usr/local/lib/libopencv_dnn.so.4.0.0
sudo rm /usr/local/lib/libopencv_dnn.so.4.0
sudo rm /usr/local/lib/libopencv_dnn.so
sudo rm /usr/local/include/cv2/opencv2/dnn.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/all_layers.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/dict.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/dnn.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/dnn.inl.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/layer.details.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/layer.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/shape_utils.hpp
sudo rm /usr/local/include/cv2/opencv2/dnn/version.hpp
sudo rm /usr/local/lib/libopencv_freetype.so.4.0.0
sudo rm /usr/local/lib/libopencv_freetype.so.4.0
sudo rm /usr/local/lib/libopencv_freetype.so
sudo rm /usr/local/include/cv2/opencv2/freetype.hpp
sudo rm /usr/local/lib/libopencv_fuzzy.so.4.0.0
sudo rm /usr/local/lib/libopencv_fuzzy.so.4.0
sudo rm /usr/local/lib/libopencv_fuzzy.so
sudo rm /usr/local/include/cv2/opencv2/fuzzy.hpp
sudo rm /usr/local/include/cv2/opencv2/fuzzy/fuzzy_F0_math.hpp
sudo rm /usr/local/include/cv2/opencv2/fuzzy/fuzzy_F1_math.hpp
sudo rm /usr/local/include/cv2/opencv2/fuzzy/fuzzy_image.hpp
sudo rm /usr/local/include/cv2/opencv2/fuzzy/types.hpp
sudo rm /usr/local/lib/libopencv_gapi.so.4.0.0
sudo rm /usr/local/lib/libopencv_gapi.so.4.0
sudo rm /usr/local/lib/libopencv_gapi.so
sudo rm /usr/local/include/cv2/opencv2/gapi.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/core.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/garg.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/garray.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gcall.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gcommon.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gcompiled.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gcompoundkernel.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gcomputation.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gkernel.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gmat.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gmetaarg.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gproto.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gscalar.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gtype_traits.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gtyped.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/opencv_includes.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/operators.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/any.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/compiler_hints.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/optional.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/throw.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/util.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/util/variant.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/cpu/core.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/cpu/gcpukernel.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/cpu/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gpu/core.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gpu/ggpukernel.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/gpu/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/fluid/core.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/fluid/gfluidbuffer.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/fluid/gfluidkernel.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/fluid/imgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/assert.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/convert.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/cvdefs.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/exports.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/mat.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/saturate.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/scalar.hpp
sudo rm /usr/local/include/cv2/opencv2/gapi/own/types.hpp
sudo rm /usr/local/lib/libopencv_hfs.so.4.0.0
sudo rm /usr/local/lib/libopencv_hfs.so.4.0
sudo rm /usr/local/lib/libopencv_hfs.so
sudo rm /usr/local/include/cv2/opencv2/hfs.hpp
sudo rm /usr/local/lib/libopencv_img_hash.so.4.0.0
sudo rm /usr/local/lib/libopencv_img_hash.so.4.0
sudo rm /usr/local/lib/libopencv_img_hash.so
sudo rm /usr/local/include/cv2/opencv2/img_hash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/average_hash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/block_mean_hash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/color_moment_hash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/img_hash_base.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/marr_hildreth_hash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/phash.hpp
sudo rm /usr/local/include/cv2/opencv2/img_hash/radial_variance_hash.hpp
sudo rm /usr/local/lib/libopencv_imgcodecs.so.4.0.0
sudo rm /usr/local/lib/libopencv_imgcodecs.so.4.0
sudo rm /usr/local/lib/libopencv_imgcodecs.so
sudo rm /usr/local/include/cv2/opencv2/imgcodecs.hpp
sudo rm /usr/local/include/cv2/opencv2/imgcodecs/imgcodecs.hpp
sudo rm /usr/local/include/cv2/opencv2/imgcodecs/imgcodecs_c.h
sudo rm /usr/local/include/cv2/opencv2/imgcodecs/ios.h
sudo rm /usr/local/lib/libopencv_photo.so.4.0.0
sudo rm /usr/local/lib/libopencv_photo.so.4.0
sudo rm /usr/local/lib/libopencv_photo.so
sudo rm /usr/local/include/cv2/opencv2/photo.hpp
sudo rm /usr/local/include/cv2/opencv2/photo/cuda.hpp
sudo rm /usr/local/include/cv2/opencv2/photo/photo.hpp
sudo rm /usr/local/lib/libopencv_videoio.so.4.0.0
sudo rm /usr/local/lib/libopencv_videoio.so.4.0
sudo rm /usr/local/lib/libopencv_videoio.so
sudo rm /usr/local/include/cv2/opencv2/videoio.hpp
sudo rm /usr/local/include/cv2/opencv2/videoio/registry.hpp
sudo rm /usr/local/include/cv2/opencv2/videoio/videoio.hpp
sudo rm /usr/local/include/cv2/opencv2/videoio/cap_ios.h
sudo rm /usr/local/include/cv2/opencv2/videoio/videoio_c.h
sudo rm /usr/local/lib/libopencv_cudacodec.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudacodec.so.4.0
sudo rm /usr/local/lib/libopencv_cudacodec.so
sudo rm /usr/local/include/cv2/opencv2/cudacodec.hpp
sudo rm /usr/local/lib/libopencv_highgui.so.4.0.0
sudo rm /usr/local/lib/libopencv_highgui.so.4.0
sudo rm /usr/local/lib/libopencv_highgui.so
sudo rm /usr/local/include/cv2/opencv2/highgui.hpp
sudo rm /usr/local/include/cv2/opencv2/highgui/highgui.hpp
sudo rm /usr/local/include/cv2/opencv2/highgui/highgui_c.h
sudo rm /usr/local/lib/libopencv_bioinspired.so.4.0.0
sudo rm /usr/local/lib/libopencv_bioinspired.so.4.0
sudo rm /usr/local/lib/libopencv_bioinspired.so
sudo rm /usr/local/include/cv2/opencv2/bioinspired.hpp
sudo rm /usr/local/include/cv2/opencv2/bioinspired/bioinspired.hpp
sudo rm /usr/local/include/cv2/opencv2/bioinspired/retina.hpp
sudo rm /usr/local/include/cv2/opencv2/bioinspired/retinafasttonemapping.hpp
sudo rm /usr/local/include/cv2/opencv2/bioinspired/transientareassegmentationmodule.hpp
sudo rm /usr/local/lib/libopencv_dnn_objdetect.so.4.0.0
sudo rm /usr/local/lib/libopencv_dnn_objdetect.so.4.0
sudo rm /usr/local/lib/libopencv_dnn_objdetect.so
sudo rm /usr/local/include/cv2/opencv2/core_detect.hpp
sudo rm /usr/local/lib/libopencv_features2d.so.4.0.0
sudo rm /usr/local/lib/libopencv_features2d.so.4.0
sudo rm /usr/local/lib/libopencv_features2d.so
sudo rm /usr/local/include/cv2/opencv2/features2d.hpp
sudo rm /usr/local/include/cv2/opencv2/features2d/features2d.hpp
sudo rm /usr/local/include/cv2/opencv2/features2d/hal/interface.h
sudo rm /usr/local/lib/libopencv_line_descriptor.so.4.0.0
sudo rm /usr/local/lib/libopencv_line_descriptor.so.4.0
sudo rm /usr/local/lib/libopencv_line_descriptor.so
sudo rm /usr/local/include/cv2/opencv2/line_descriptor.hpp
sudo rm /usr/local/include/cv2/opencv2/line_descriptor/descriptor.hpp
sudo rm /usr/local/lib/libopencv_saliency.so.4.0.0
sudo rm /usr/local/lib/libopencv_saliency.so.4.0
sudo rm /usr/local/lib/libopencv_saliency.so
sudo rm /usr/local/include/cv2/opencv2/saliency.hpp
sudo rm /usr/local/include/cv2/opencv2/saliency/saliencyBaseClasses.hpp
sudo rm /usr/local/include/cv2/opencv2/saliency/saliencySpecializedClasses.hpp
sudo rm /usr/local/lib/libopencv_text.so.4.0.0
sudo rm /usr/local/lib/libopencv_text.so.4.0
sudo rm /usr/local/lib/libopencv_text.so
sudo rm /usr/local/include/cv2/opencv2/text.hpp
sudo rm /usr/local/include/cv2/opencv2/text/erfilter.hpp
sudo rm /usr/local/include/cv2/opencv2/text/ocr.hpp
sudo rm /usr/local/include/cv2/opencv2/text/textDetector.hpp
sudo rm /usr/local/lib/libopencv_calib3d.so.4.0.0
sudo rm /usr/local/lib/libopencv_calib3d.so.4.0
sudo rm /usr/local/lib/libopencv_calib3d.so
sudo rm /usr/local/include/cv2/opencv2/calib3d.hpp
sudo rm /usr/local/include/cv2/opencv2/calib3d/calib3d.hpp
sudo rm /usr/local/include/cv2/opencv2/calib3d/calib3d_c.h
sudo rm /usr/local/lib/libopencv_ccalib.so.4.0.0
sudo rm /usr/local/lib/libopencv_ccalib.so.4.0
sudo rm /usr/local/lib/libopencv_ccalib.so
sudo rm /usr/local/include/cv2/opencv2/ccalib.hpp
sudo rm /usr/local/include/cv2/opencv2/ccalib/multicalib.hpp
sudo rm /usr/local/include/cv2/opencv2/ccalib/omnidir.hpp
sudo rm /usr/local/include/cv2/opencv2/ccalib/randpattern.hpp
sudo rm /usr/local/lib/libopencv_cudafeatures2d.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudafeatures2d.so.4.0
sudo rm /usr/local/lib/libopencv_cudafeatures2d.so
sudo rm /usr/local/include/cv2/opencv2/cudafeatures2d.hpp
sudo rm /usr/local/lib/libopencv_cudastereo.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudastereo.so.4.0
sudo rm /usr/local/lib/libopencv_cudastereo.so
sudo rm /usr/local/include/cv2/opencv2/cudastereo.hpp
sudo rm /usr/local/lib/libopencv_datasets.so.4.0.0
sudo rm /usr/local/lib/libopencv_datasets.so.4.0
sudo rm /usr/local/lib/libopencv_datasets.so
sudo rm /usr/local/include/cv2/opencv2/datasets/ar_hmdb.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/ar_sports.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/dataset.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/fr_adience.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/fr_lfw.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/gr_chalearn.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/gr_skig.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/hpe_humaneva.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/hpe_parse.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/ir_affine.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/ir_robot.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/is_bsds.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/is_weizmann.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/msm_epfl.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/msm_middlebury.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/or_imagenet.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/or_mnist.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/or_pascal.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/or_sun.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/pd_caltech.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/pd_inria.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/slam_kitti.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/slam_tumindoor.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/tr_chars.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/tr_icdar.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/tr_svt.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/track_alov.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/track_vot.hpp
sudo rm /usr/local/include/cv2/opencv2/datasets/util.hpp
sudo rm /usr/local/lib/libopencv_objdetect.so.4.0.0
sudo rm /usr/local/lib/libopencv_objdetect.so.4.0
sudo rm /usr/local/lib/libopencv_objdetect.so
sudo rm /usr/local/include/cv2/opencv2/objdetect.hpp
sudo rm /usr/local/include/cv2/opencv2/objdetect/detection_based_tracker.hpp
sudo rm /usr/local/include/cv2/opencv2/objdetect/objdetect.hpp
sudo rm /usr/local/lib/libopencv_rgbd.so.4.0.0
sudo rm /usr/local/lib/libopencv_rgbd.so.4.0
sudo rm /usr/local/lib/libopencv_rgbd.so
sudo rm /usr/local/include/cv2/opencv2/rgbd.hpp
sudo rm /usr/local/include/cv2/opencv2/rgbd/depth.hpp
sudo rm /usr/local/include/cv2/opencv2/rgbd/kinfu.hpp
sudo rm /usr/local/include/cv2/opencv2/rgbd/linemod.hpp
sudo rm /usr/local/lib/libopencv_shape.so.4.0.0
sudo rm /usr/local/lib/libopencv_shape.so.4.0
sudo rm /usr/local/lib/libopencv_shape.so
sudo rm /usr/local/include/cv2/opencv2/shape.hpp
sudo rm /usr/local/include/cv2/opencv2/shape/emdL1.hpp
sudo rm /usr/local/include/cv2/opencv2/shape/hist_cost.hpp
sudo rm /usr/local/include/cv2/opencv2/shape/shape.hpp
sudo rm /usr/local/include/cv2/opencv2/shape/shape_distance.hpp
sudo rm /usr/local/include/cv2/opencv2/shape/shape_transformer.hpp
sudo rm /usr/local/lib/libopencv_stereo.so.4.0.0
sudo rm /usr/local/lib/libopencv_stereo.so.4.0
sudo rm /usr/local/lib/libopencv_stereo.so
sudo rm /usr/local/include/cv2/opencv2/stereo.hpp
sudo rm /usr/local/include/cv2/opencv2/stereo/descriptor.hpp
sudo rm /usr/local/include/cv2/opencv2/stereo/matching.hpp
sudo rm /usr/local/include/cv2/opencv2/stereo/stereo.hpp
sudo rm /usr/local/lib/libopencv_structured_light.so.4.0.0
sudo rm /usr/local/lib/libopencv_structured_light.so.4.0
sudo rm /usr/local/lib/libopencv_structured_light.so
sudo rm /usr/local/include/cv2/opencv2/structured_light.hpp
sudo rm /usr/local/include/cv2/opencv2/structured_light/graycodepattern.hpp
sudo rm /usr/local/include/cv2/opencv2/structured_light/sinusoidalpattern.hpp
sudo rm /usr/local/include/cv2/opencv2/structured_light/structured_light.hpp
sudo rm /usr/local/lib/libopencv_video.so.4.0.0
sudo rm /usr/local/lib/libopencv_video.so.4.0
sudo rm /usr/local/lib/libopencv_video.so
sudo rm /usr/local/include/cv2/opencv2/video.hpp
sudo rm /usr/local/include/cv2/opencv2/video/background_segm.hpp
sudo rm /usr/local/include/cv2/opencv2/video/tracking.hpp
sudo rm /usr/local/include/cv2/opencv2/video/video.hpp
sudo rm /usr/local/lib/libopencv_xfeatures2d.so.4.0.0
sudo rm /usr/local/lib/libopencv_xfeatures2d.so.4.0
sudo rm /usr/local/lib/libopencv_xfeatures2d.so
sudo rm /usr/local/include/cv2/opencv2/xfeatures2d.hpp
sudo rm /usr/local/include/cv2/opencv2/xfeatures2d/cuda.hpp
sudo rm /usr/local/include/cv2/opencv2/xfeatures2d/nonfree.hpp
sudo rm /usr/local/lib/libopencv_ximgproc.so.4.0.0
sudo rm /usr/local/lib/libopencv_ximgproc.so.4.0
sudo rm /usr/local/lib/libopencv_ximgproc.so
sudo rm /usr/local/include/cv2/opencv2/ximgproc.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/brightedges.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/color_match.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/deriche_filter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/disparity_filter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/edge_filter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/edgeboxes.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/edgepreserving_filter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/estimated_covariance.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/fast_hough_transform.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/fast_line_detector.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/fourier_descriptors.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/lsc.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/paillou_filter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/peilin.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/ridgefilter.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/run_length_morphology.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/seeds.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/segmentation.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/slic.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/sparse_match_interpolator.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/structured_edge_detection.hpp
sudo rm /usr/local/include/cv2/opencv2/ximgproc/weighted_median_filter.hpp
sudo rm /usr/local/lib/libopencv_xobjdetect.so.4.0.0
sudo rm /usr/local/lib/libopencv_xobjdetect.so.4.0
sudo rm /usr/local/lib/libopencv_xobjdetect.so
sudo rm /usr/local/include/cv2/opencv2/xobjdetect.hpp
sudo rm /usr/local/bin/opencv_waldboost_detector
sudo rm /usr/local/lib/libopencv_aruco.so.4.0.0
sudo rm /usr/local/lib/libopencv_aruco.so.4.0
sudo rm /usr/local/lib/libopencv_aruco.so
sudo rm /usr/local/include/cv2/opencv2/aruco.hpp
sudo rm /usr/local/include/cv2/opencv2/aruco/charuco.hpp
sudo rm /usr/local/include/cv2/opencv2/aruco/dictionary.hpp
sudo rm /usr/local/lib/libopencv_bgsegm.so.4.0.0
sudo rm /usr/local/lib/libopencv_bgsegm.so.4.0
sudo rm /usr/local/lib/libopencv_bgsegm.so
sudo rm /usr/local/include/cv2/opencv2/bgsegm.hpp
sudo rm /usr/local/lib/libopencv_cudabgsegm.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudabgsegm.so.4.0
sudo rm /usr/local/lib/libopencv_cudabgsegm.so
sudo rm /usr/local/include/cv2/opencv2/cudabgsegm.hpp
sudo rm /usr/local/lib/libopencv_cudalegacy.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudalegacy.so.4.0
sudo rm /usr/local/lib/libopencv_cudalegacy.so
sudo rm /usr/local/include/cv2/opencv2/cudalegacy.hpp
sudo rm /usr/local/include/cv2/opencv2/cudalegacy/NCV.hpp
sudo rm /usr/local/include/cv2/opencv2/cudalegacy/NCVBroxOpticalFlow.hpp
sudo rm /usr/local/include/cv2/opencv2/cudalegacy/NCVHaarObjectDetection.hpp
sudo rm /usr/local/include/cv2/opencv2/cudalegacy/NCVPyramid.hpp
sudo rm /usr/local/include/cv2/opencv2/cudalegacy/NPP_staging.hpp
sudo rm /usr/local/lib/libopencv_cudaobjdetect.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudaobjdetect.so.4.0
sudo rm /usr/local/lib/libopencv_cudaobjdetect.so
sudo rm /usr/local/include/cv2/opencv2/cudaobjdetect.hpp
sudo rm /usr/local/lib/libopencv_dpm.so.4.0.0
sudo rm /usr/local/lib/libopencv_dpm.so.4.0
sudo rm /usr/local/lib/libopencv_dpm.so
sudo rm /usr/local/include/cv2/opencv2/dpm.hpp
sudo rm /usr/local/lib/libopencv_face.so.4.0.0
sudo rm /usr/local/lib/libopencv_face.so.4.0
sudo rm /usr/local/lib/libopencv_face.so
sudo rm /usr/local/include/cv2/opencv2/face.hpp
sudo rm /usr/local/include/cv2/opencv2/face/bif.hpp
sudo rm /usr/local/include/cv2/opencv2/face/face_alignment.hpp
sudo rm /usr/local/include/cv2/opencv2/face/facemark.hpp
sudo rm /usr/local/include/cv2/opencv2/face/facemarkAAM.hpp
sudo rm /usr/local/include/cv2/opencv2/face/facemarkLBF.hpp
sudo rm /usr/local/include/cv2/opencv2/face/facemark_train.hpp
sudo rm /usr/local/include/cv2/opencv2/face/facerec.hpp
sudo rm /usr/local/include/cv2/opencv2/face/mace.hpp
sudo rm /usr/local/include/cv2/opencv2/face/predict_collector.hpp
sudo rm /usr/local/lib/libopencv_optflow.so.4.0.0
sudo rm /usr/local/lib/libopencv_optflow.so.4.0
sudo rm /usr/local/lib/libopencv_optflow.so
sudo rm /usr/local/include/cv2/opencv2/optflow.hpp
sudo rm /usr/local/include/cv2/opencv2/optflow/motempl.hpp
sudo rm /usr/local/include/cv2/opencv2/optflow/pcaflow.hpp
sudo rm /usr/local/include/cv2/opencv2/optflow/sparse_matching_gpc.hpp
sudo rm /usr/local/lib/libopencv_stitching.so.4.0.0
sudo rm /usr/local/lib/libopencv_stitching.so.4.0
sudo rm /usr/local/lib/libopencv_stitching.so
sudo rm /usr/local/include/cv2/opencv2/stitching.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/warpers.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/autocalib.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/blenders.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/camera.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/exposure_compensate.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/matchers.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/motion_estimators.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/seam_finders.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/timelapsers.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/util.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/util_inl.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/warpers.hpp
sudo rm /usr/local/include/cv2/opencv2/stitching/detail/warpers_inl.hpp
sudo rm /usr/local/lib/libopencv_tracking.so.4.0.0
sudo rm /usr/local/lib/libopencv_tracking.so.4.0
sudo rm /usr/local/lib/libopencv_tracking.so
sudo rm /usr/local/include/cv2/opencv2/tracking.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/feature.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/kalman_filters.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/onlineBoosting.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/onlineMIL.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/tldDataset.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/tracker.hpp
sudo rm /usr/local/include/cv2/opencv2/tracking/tracking.hpp
sudo rm /usr/local/lib/libopencv_cudaoptflow.so.4.0.0
sudo rm /usr/local/lib/libopencv_cudaoptflow.so.4.0
sudo rm /usr/local/lib/libopencv_cudaoptflow.so
sudo rm /usr/local/include/cv2/opencv2/cudaoptflow.hpp
sudo rm /usr/local/lib/libopencv_superres.so.4.0.0
sudo rm /usr/local/lib/libopencv_superres.so.4.0
sudo rm /usr/local/lib/libopencv_superres.so
sudo rm /usr/local/include/cv2/opencv2/superres.hpp
sudo rm /usr/local/include/cv2/opencv2/superres/optical_flow.hpp
sudo rm /usr/local/lib/libopencv_videostab.so.4.0.0
sudo rm /usr/local/lib/libopencv_videostab.so.4.0
sudo rm /usr/local/lib/libopencv_videostab.so
sudo rm /usr/local/include/cv2/opencv2/videostab.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/deblurring.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/fast_marching.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/fast_marching_inl.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/frame_source.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/global_motion.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/inpainting.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/log.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/motion_core.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/motion_stabilizing.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/optical_flow.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/outlier_rejection.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/ring_buffer.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/stabilizer.hpp
sudo rm /usr/local/include/cv2/opencv2/videostab/wobble_suppression.hpp
sudo rm /usr/local/python/cv2/python-2.7/cv2.so
sudo rm /usr/local/python/cv2/config-2.7.py
sudo rm /usr/local/python/cv2/python-3.6/cv2.cpython-36m-aarch64-linux-gnu.so
sudo rm /usr/local/python/cv2/config-3.6.py
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_eye.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_eye_tree_eyeglasses.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalcatface.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalcatface_extended.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalface_alt.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalface_alt2.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalface_alt_tree.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_frontalface_default.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_fullbody.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_lefteye_2splits.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_licence_plate_rus_16stages.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_lowerbody.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_profileface.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_righteye_2splits.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_russian_plate_number.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_smile.xml
sudo rm /usr/local/share/cv2/haarcascades/haarcascade_upperbody.xml
sudo rm /usr/local/share/cv2/lbpcascades/lbpcascade_frontalcatface.xml
sudo rm /usr/local/share/cv2/lbpcascades/lbpcascade_frontalface.xml
sudo rm /usr/local/share/cv2/lbpcascades/lbpcascade_frontalface_improved.xml
sudo rm /usr/local/share/cv2/lbpcascades/lbpcascade_profileface.xml
sudo rm /usr/local/share/cv2/lbpcascades/lbpcascade_silverware.xml
sudo rm /usr/local/bin/opencv_annotation
sudo rm /usr/local/bin/opencv_visualisation
sudo rm /usr/local/bin/opencv_interactive-calibration
sudo rm /usr/local/bin/opencv_version